version: "3.7"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=server
      - FLASK_ENV=development
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend
